Band.create!(name: 'Arcade Fire', id: 1)
Band.create!(name: 'Joy Division', id: 2)
Band.create!(name: 'Los Planetas', id: 3)
Album.create!(title: 'The Suburbs', band_id: 1)
Album.create!(title: 'Unknown Pleasures', band_id: 2)
Album.create!(title: 'Reflektor', band_id: 1)
Album.create!(title: 'Unidad de Desplazamiento', band_id: 3)